# Generated by Django 5.2.8 on 2025-11-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usermessages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_at"]},
        ),
    ]
