# Generated by Django 5.2.8 on 2025-12-01 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_is_deleted_post_parent_post_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(db_index=True, max_length=100, unique=True)),
                ("use_count", models.IntegerField(default=0)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PostHashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="post",
            name="bookmark_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="is_quote_tweet",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="quote_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="reply_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="retweet_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="retweet_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retweets",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="root_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_posts",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(blank=True, default="", max_length=280),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["follower"], name="posts_follo_followe_5565c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["following"], name="posts_follo_followi_6451f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["following", "created_at"],
                name="posts_follo_followi_cb550f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["post", "created_at"], name="posts_like_post_id_425a42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(fields=["user"], name="posts_like_user_id_842d1b_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["root_post"], name="posts_post_root_po_89b3f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["retweet_of"], name="posts_post_retweet_352e68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["retweet_of", "user"], name="posts_post_retweet_fa702a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["created_at"], name="posts_post_created_dadbfe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["is_deleted", "created_at"],
                name="posts_post_is_dele_23997e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["root_post", "created_at"], name="posts_post_root_po_979633_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hashtag",
            index=models.Index(fields=["tag"], name="posts_hasht_tag_7a6858_idx"),
        ),
        migrations.AddIndex(
            model_name="hashtag",
            index=models.Index(
                fields=["use_count", "last_used_at"],
                name="posts_hasht_use_cou_3eb78e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hashtag",
            index=models.Index(
                fields=["last_used_at"], name="posts_hasht_last_us_643a2c_idx"
            ),
        ),
        migrations.AddField(
            model_name="mention",
            name="mentioned_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentioned_in",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mention",
            name="mentioner_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="has_mentioned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mention",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentions",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="posthashtag",
            name="hashtag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hashtag_posts",
                to="posts.hashtag",
            ),
        ),
        migrations.AddField(
            model_name="posthashtag",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_hashtags",
                to="posts.post",
            ),
        ),
        migrations.AddIndex(
            model_name="mention",
            index=models.Index(
                fields=["mentioned_user"], name="posts_menti_mention_f52c3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mention",
            index=models.Index(fields=["post"], name="posts_menti_post_id_63bd5f_idx"),
        ),
        migrations.AddIndex(
            model_name="mention",
            index=models.Index(
                fields=["mentioned_user", "created_at"],
                name="posts_menti_mention_bb9f6d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mention",
            unique_together={("post", "mentioned_user")},
        ),
        migrations.AddIndex(
            model_name="posthashtag",
            index=models.Index(
                fields=["post", "hashtag"], name="posts_posth_post_id_cf2f78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="posthashtag",
            index=models.Index(
                fields=["hashtag"], name="posts_posth_hashtag_d73639_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="posthashtag",
            unique_together={("post", "hashtag")},
        ),
    ]
