# Generated by Django 5.2.8 on 2025-11-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "posts",
            "0002_alter_follow_follower_alter_follow_following_and_more",
        ),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
