# Generated by Django 5.2.8 on 2025-12-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userprofile_avatar_url_userprofile_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_verification_key",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reset_token",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
