# Generated by Django 5.2.8 on 2025-12-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userprofile_email_verification_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="reset_token_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
