# Generated by Django 5.2.8 on 2025-12-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userprofile_reset_token_expires"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_verification_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_verification_key_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_verification_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
