# Generated by Django 5.2.8 on 2025-12-04 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_userprofile_email_verification_attempts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("account", "Account Verification"),
                            ("password_reset",
                             "Password Reset Pre-Verification"),
                            ("email_change", "Email Change Verification"),
                            ("resend", "Resend Request"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Email Sent"),
                            ("verified", "Successfully Verified"),
                            ("expired", "Link Expired"),
                            ("failed", "Verification Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address",
                 models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="users_email_user_id_8029b4_idx",
                    ),
                    models.Index(
                        fields=["email", "status", "created_at"],
                        name="users_email_email_c7e431_idx",
                    ),
                    models.Index(
                        fields=["verification_type"],
                        name="users_email_verific_c364f0_idx",
                    ),
                ],
            },
        ),
    ]
