# Generated by Django 5.2.8 on 2025-12-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_emailverificationlog"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="emailverificationlog",
            name="users_email_verific_c364f0_idx",
        ),
        migrations.RemoveField(
            model_name="emailverificationlog",
            name="verification_type",
        ),
    ]
