# Generated by Django 5.2.8 on 2025-12-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_verification_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailverificationlog",
            name="ip_address",
        ),
    ]
